- id: cargo-fmt-conda
  name: cargo-fmt-conda
  description: "Run 'cargo fmt' for formatting Rust sources"
  entry: 'cargo fmt --'
  language: conda
  require_serial: false
  types: [rust]
- id: clippy-conda
  name: clippy-conda
  description: "Run 'clippy' to lint Rust sources"
  entry: 'cargo clippy --all-targets --all-features --workspace -- -D warnings'
  pass_filenames: false
  language: conda
  require_serial: false
  types: [rust]
